<a href="https://colab.research.google.com/github/M-Dinesh-14/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

NumPy is an open source mathematical and scientific computing library for Python programming tasks it is denoted by np.

* The NumPy library offers a collection of high-level mathematical functions including support for multi-dimensional arrays, masked arrays and matrices.
* A Python list is most suitable for data storage and not ideally intended for math tasks, while a NumPy list can easily support math-intensive tasks.

# ndarrays

The primary data structure in NumPy is the N-dimensional array -- called an ndarray or simply an array.
*  Every ndarray is a fixed-size array that is kept in memory and contains the same type of data such as integer or floating-point numbers.

In [ ]:
p

# Applications of numpy.
* Matplotlib.
* Pandas.
* scikit-image.
* scikit-learn.
* SciPy.

# import

import command to make the module name more relevant, readable or easier to reference.

example of N-dimention by using array by slicing

---





# copy

In [ ]:
import numpy as np
d = np.array([2,3,45,4,3])
x = d.copy()
d[0] = 42
print(d)
print(x)

[42  3 45  4  3]
[ 2  3 45  4  3]


# shape

In [ ]:
import numpy as np
d = np.array([2,3,45,4,3])
x = d.shape
print(x)

(5,)


In [28]:
#reshape
d=np.array([1,2,3,4,5,6,7,8,9,0,11,12])
print(d)
a=d.reshape(4,3)
print(a)
print(a.size)# size of the array

[ 1  2  3  4  5  6  7  8  9  0 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 11 12]]
12


In [30]:
d= np.array([[2,5,1],[9,4,7]]) #sort
print(d)
s=np.sort(d)
print(s)

[[2 5 1]
 [9 4 7]]
[[1 2 5]
 [4 7 9]]


In [20]:
ones=np.ones((4,4),int)
print(ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


0-d t0 0-d

In [ ]:
import numpy as np
d = np.array([2,3,4,5,4,3])
print(d[1:2])

[3]


0-d to 1-d

In [ ]:
import numpy as np
d = np.array([1,2,3,4,5,6,7,8])
print(d[:4])
print(d[4:8])


[1 2 3 4]
[5 6 7 8]


0-d to 2-d

In [ ]:
import numpy as np
d = np.array([1,2,3,4,5,6,7,8])
print(d[:3])
print(d[3:6])
print(d[6:8])

[1 2 3]
[4 5 6]
[7 8]


0-d to 3-d

In [ ]:
import numpy as np
d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(d[:3])
print(d[3:6])
print(d[6:9])
print(d[9:12])

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


1-d t0 2-d

In [ ]:
import numpy as np
d = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(d[1, 0:4])
print(d[1, 4:6])
print(d[0, 3:6])

[ 7  8  9 10]
[11 12]
[4 5 6]


1-d to 3-d

In [ ]:
import numpy as np
d = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(d[0, 0:4])
print(d[0,  4:6])
print(d[0,  3:6])
print(d[1,2:6])

[1 2 3 4]
[5 6]
[4 5 6]
[ 9 10 11 12]


2-d t0 1-d

In [4]:
import numpy as np
d = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
print(d[ 0:4,4:6])
print(d.ndim)



[[ 5  6]
 [11 12]
 [17 18]]
2


2-d to 2-d

In [3]:
import numpy as np
d = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
print(d[0:2, 2])
print(d[2, 4:6])
print(d[0:2, 1:4])
print(d.ndim)


[3 9]
[17 18]
[[ 2  3  4]
 [ 8  9 10]]
2


2-d to 3-d

In [19]:
import numpy as np
d = np.array([[[[1,2,3,4,5,6],[7,8,9,10,11,12]],[[13,14,15,16,17,18],[19,20,21,22,23,24]]]])
print(d[0,0:2])
print(d[[1,5]])
print(d[2,0:3,3:5,5:7])
print(d.ndim)


[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


IndexError: index 1 is out of bounds for axis 0 with size 1

3-d t0 1-d

In [9]:
import numpy as np
d = np.array([[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]]])
print(d[0,:4])
print(d[2:5,3:4])
print(d[4:6,5:7])
print(d.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]
[]
[]
4


3-d to 2-d

In [12]:
import numpy as np
d = np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],[[13,14,15,16,17,18],[19,20,21,22,23,24]]])
print(d[0,:2])
print(d[1,2:3,0:2])
print(d[2:4,3:4,3:3])
print(d.ndim)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[]
[]
3


In [24]:
d=np.array([[[2,4,3],[5,6,7],[8,9,10]], [[0,13,14],[2,3,16],[5,3,6]],
                    [[66,7,7],[2,3,4],[9,7,8]]])


In [25]:
print("dime",d)
print("shape of array",d.shape)
print(" shape",d.ndim)
print("Acessing of value",d[2,2,1])
print("length :",len(d))

dime [[[ 2  4  3]
  [ 5  6  7]
  [ 8  9 10]]

 [[ 0 13 14]
  [ 2  3 16]
  [ 5  3  6]]

 [[66  7  7]
  [ 2  3  4]
  [ 9  7  8]]]
shape of array (3, 3, 3)
 shape 3
Acessing of value 7
length : 3


In [32]:
print("min",np.min(d))
print("max",np.max(d))
print("sum",np.sum(d))
print("mean",np.mean(d))
print("avg",np.average(d))

min 1
max 9
sum 28
mean 4.666666666666667
avg 4.666666666666667
